---
Name: intranet_config
---
File:
  extensions:
    - TaxonomyFileExtension
SiteTree:
  extensions:
    - WorkflowEmbargoExpiryExtension
Member:
  extensions:
    - MemberListExtension
TimelineController:
  extensions:
    - TimelineIntranetExtension
